site_name: Inferno Help Docs
repo_url: https://github.com/InfernoMfg/help-docs
edit_uri: edit/main/docs/
site_url: https://infernomfg.github.io/help-docs/
copyright: © Inferno Mfg. Corp. 2022, All rights reserved
site_author: ntno

nav:
    - About: 'index.md'
    - Contact: 'contact.md'
    - 'Gage Selector Help': 'gage-selector.md'
    - 'Datasheet Wizard Help': 'datasheet-wizard.md'
    
markdown_extensions:
  - admonition
  - pymdownx.tabbed
  - meta
  - md_in_html  
  - attr_list
  - toc:
      permalink: true

theme:
  name: material
  favicon: img/favicon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.integrate
  palette:
    primary: grey
    accent: red
